/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 09 15:01:29 GMT 2025
 */

package com.example.calculator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.example.calculator.Calculator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true, separateClassLoader = true) 
public class Calculator_ESTest extends Calculator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.sub((-1413), (-1761));
      assertEquals((-3174), int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.divide(1336, 1336);
      assertEquals(1, int0);
  }
}
